# Generated by Django 4.0.4 on 2022-05-09 13:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_remove_student_name_remove_teacher_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherstudent',
            old_name='Student',
            new_name='student',
        ),
    ]
