# Generated by Django 4.0.4 on 2022-05-10 09:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="first_name",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="student",
            name="last_name",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="first_name",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="teacher",
            name="last_name",
            field=models.CharField(default=False, max_length=50),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="is_star",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="student",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="teacher",
            field=models.ForeignKey(
                default=False,
                on_delete=django.db.models.deletion.CASCADE,
                to="app.teacher",
            ),
        ),
    ]
