# Generated by Django 4.0.4 on 2022-05-12 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("app", "0004_remove_student_teacher"),
    ]

    operations = [
        migrations.AlterField(
            model_name="teacherstudent",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="student1",
                to="app.student",
            ),
        ),
        migrations.AlterField(
            model_name="teacherstudent",
            name="teacher",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="teacher1",
                to="app.teacher",
            ),
        ),
    ]
